// Generated by https://quicktype.io

import type { BasePaginatorResponse } from '@/services/types'

export type GetAPIToolProvidersWithPageResp = BasePaginatorResponse<GetAPIToolProvidersWithPage>

export type GetAPIToolProvidersWithPageParams = {
  search_word?: string
  current_page?: number
  page_size?: number
}

export interface GetAPIToolProvidersWithPage {
  created_at: number
  description: string
  headers: Header[]
  icon: string
  id: string
  name: string
  tools: Tool[]
}

export const isGetAPIToolProvidersWithPage = (data: any): data is GetAPIToolProvidersWithPage => {
  return (
    'created_at' in data &&
    'description' in data &&
    'headers' in data &&
    'icon' in data &&
    'id' in data &&
    'name' in data &&
    'tools' in data
  )
}

export interface Tool {
  description: string
  id: string
  inputs: Input[]
  name: string
}

export interface Input {
  description: string
  name: string
  required: string
  type: string
}

export interface CreateAPIToolProviderReq {
  headers: Header[]
  icon: string
  name: string
  openapi_schema: string
}

export interface UpdateAPIToolProviderReq {
  headers: Header[]
  icon: string
  name: string
  openapi_schema: string
}

export interface GetAPIToolProviderResp {
  created_at: number
  headers: Header[]
  icon: string
  id: string
  name: string
  openapi_schema: string
}

export interface Header {
  name: string
  value: string
}
