export enum Theme {
  light = 'light-plus',
  dark = 'dark-plus',
  github = 'github',
  githubLight = 'github-light',
  githubDark = 'github-dark',
  vitesseLight = 'vitesse-light',
  vitesseDark = 'vitesse-dark',
  andromeeda = 'andromeeda',
  catppuccinFrappe = 'catppuccin-frappe',
  monokai = 'monokai',
  tomorrow = 'tomorrow',
  solarizedDark = 'solarized-dark',
  solarizedLight = 'solarized-light',
  vsLight = 'vs',
  vsDark = 'vs-dark',
  hcBlack = 'hc-black',
  hcLight = 'hc-light',
  idle = 'idle',
  Active4D = 'Active4D',
}
